"""add installment fields

Revision ID: 1dcb12179e52
Revises: f23f740ae5f2
Create Date: 2026-05-02 22:08:55.170271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dcb12179e52'
down_revision: Union[str, None] = 'f23f740ae5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('installment_current', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('installment_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'installment_total')
    op.drop_column('transactions', 'installment_current')
    # ### end Alembic commands ###
